[package]
name = "hello-world-solana"
version = "0.1.0"
edition = "2021"
description = "A simple Hello World program for Solana"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.17"

[features]
no-entrypoint = []